# tekken_data.py
CHARACTER_MAP = {
    "0": "Paul",
    "1": "Law",
    "2": "King",
    "3": "Yoshimitsu",
    "4": "Hwoarang",
    "5": "Xiaoyu",
    "6": "Jin",
    "7": "Bryan",
    "8": "Kazuya",
    "9": "Steve",
    "10": "Jack-8",
    "11": "Asuka",
    "12": "Devil Jin",
    "13": "Feng",
    "14": "Lili",
    "15": "Dragunov",
    "16": "Leo",
    "17": "Lars",
    "18": "Alisa",
    "19": "Claudio",
    "20": "Shaheen",
    "21": "Nina",
    "22": "Lee",
    "23": "Kuma",
    "24": "Panda",
    "28": "Zafina",
    "29": "Leroy",
    "32": "Jun",
    "33": "Reina",
    "34": "Azucena",
    "35": "Victor",
    "36": "Raven",
    "38": "Eddy",
    "39": "Lidia",
    "40": "Heihachi",
    "41": "Clive",
    "42": "Anna"
}

RANK_MAP = {
    "0": "Beginner",
    "1": "1st Dan",
    "2": "2nd Dan",
    "3": "Fighter",
    "4": "Strategist",
    "5": "Combatant",
    "6": "Brawler",
    "7": "Ranger",
    "8": "Cavalry",
    "9": "Warrior",
    "10": "Assailant",
    "11": "Dominator",
    "12": "Vanquisher",
    "13": "Destroyer",
    "14": "Eliminator",
    "15": "Garyu",
    "16": "Shinryu",
    "17": "Tenryu",
    "18": "Mighty Ruler",
    "19": "Flame Ruler",
    "20": "Battle Ruler",
    "21": "Fujin",
    "22": "Raijin",
    "23": "Kishin",
    "24": "Bushin",
    "25": "Tekken King",
    "26": "Tekken Emperor",
    "27": "Tekken God",
    "28": "Tekken God Supreme",
    "29": "God of Destruction",
    "100": "God of Destruction"
}